version: '3.8'

services:
  baileys-api:
    container_name: baileys-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - '.:/app'
      - /app/node_modules
      - './prisma:/app/prisma'
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://neondb_owner:zbm5Pq8UeLMQ@ep-rough-silence-a5357t5x.us-east-2.aws.neon.tech/neondb?sslmode=require
      API_KEY: popodeperro
      OTHER_SERVICE_URL: http://host.docker.internal:3001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "npx", "prisma", "generate"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge

