FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install --quiet

# Generamos el cliente de Prisma
RUN npx prisma generate

# Copiamos el resto de los archivos
COPY . .

EXPOSE 3000

CMD [ "npm", "run", "dev" ]


